apiVersion: apps/v1
kind: Deployment
metadata:
  name: administration-service
spec:
  replicas: 1
  selector:
    matchlabels:
      app: administration-service
    template:
      metadata:
        labels:
          app: administration-service
      spec:
        containers:
        - name: administration-service
          image: paulabuscacio/administration-service:latest
          ports:
          - containerPort: 8060
---
apiVersion: v1
kind: Service
metadata:
  name: administration-service
  labels:
    app: administration-service
spec:
  type: ClusterIp
  ports:
    - port: 8060
    targetPort: 8060
selector:
  app: adminstration-service


